### PR TITLE
Rst readme

### PR DESCRIPTION
**Pull request by ivanhercaz**
I check the [PyPI page](https://pypi.org/project/pingtop/) of `pingtop` isn't rendered correctly, so I suppose it is because the README is in Markdown and the setup() doesn't have specified this format. Thus I decided to convert the markdown README to the reStructuredText format because I think this is the easier solution. It fits with the specification of another documenting tools.

### CODE REVIEW

**Comment by laixintao** [comment]
Hi, thanks!

I have tried to fix this, but somehow `text/markdown` didn't work with pypi.org. I still don't know why, some other people have the same issue. It was said that[ markdown should just works fine](https://packaging.python.org/specifications/core-metadata/#description-content-type-optional).

Anyway, let's try rst, could you please also change [this](https://github.com/laixintao/pingtop/blob/master/setup.py#L30) to `text/x-rst` ? I will try to merge and make a release.( ref: https://packaging.python.org/specifications/core-metadata/#description-content-type-optional )

**Comment by ivanhercaz** [comment]
> I have tried to fix this, but somehow `text/markdown` didn't work with pypi.org. I still don't know why, some other people have the same issue. It was said that markdown should just works fine.

It's strange but yes, I have seen another packages with this problem. At the beginning I thought it was because it isn't configured correctly, but I don't check your setup.py, so the problem is probably related with PyPI and not with this package.

> Anyway, let's try rst, could you please also change this to `text/x-rst`?

Of course! I am going to add this change and I will notify you.

**Comment by ivanhercaz** [comment]
@laixintao, changed!

**Comment by ivanhercaz** [comment]
About to make a release, #24 may be of your interest before to make it.

**Comment by laixintao** [comment]
Thanks! Looks good to me :)

**Pull request merged**
